version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/aspnetcore-health/api/v2/package
  api_key:
    secure: Msv9TA4MzbLFcLjBM7aWGpU5miHtVlwYa2MOD/CPj1iXRPx+xN3tBjf88Eq6H8GZ
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: zSrvHwgAT1PPfN+RccvIdYDk8xOdZaH4Z2HYmAkOZJ6VCk8tm0ElAlcvBgCdBOm1
  on:
    branch: master
    appveyor_repo_tag: true